USE ajedrez;   
SELECT IDPIEZA, 
TP.DESCRIPCIONDEPIEZA as TIPOPIEZA, 
-- P.DESCRIPCION as DESCRIPCION_PIEZA, 
C.DESCRIPCION as COLOR,
M.DESCRIPCION AS MATERIAL,
P.POSICION,
P.CAPACIDAD_DESPLAZAMIENTO,
P.CONDUCTA,
P.VELOCIDAD,
P.CAPACIDAD_ATAQUE,
P.FECHA_CREACION
FROM PIEZA AS P
INNER JOIN COLOR AS C ON C.IDCOLOR = P.IDCOLOR
INNER JOIN TAMANIO AS T ON T.IDTAMANIO = P.IDTAMANIO
INNER JOIN MATERIAL AS M ON M.IDMATERIAL = P.IDMATERIAL
INNER JOIN TIPOPIEZA AS TP ON TP.IDTIPOPIEZA = P.IDTIPOPIEZA
/*WHERE P.IDTIPOPIEZA IN (
SELECT IDTIPOPIEZA 
FROM TIPOPIEZA TP
WHERE TP.DESCRIPCIONDEPIEZA LIKE '%A%'
)*/

    	

        


