USE ajedrez;   
SELECT IDPIEZA, 
TP.DESCRIPCIONDEPIEZA as TIPOPIEZA, 
-- P.DESCRIPCION as DESCRIPCION_PIEZA, 
C.DESCRIPCION as COLOR,
P.POSICION,
P.MOVIMIENTO,
P.VELOCIDAD,
P.COMPORTAMIENTO,
P.FECHA_CREACION
FROM PIEZA AS P
INNER JOIN COLOR AS C ON C.IDCOLOR = P.IDCOLOR
INNER JOIN TIPOPIEZA AS TP ON TP.IDTIPOPIEZA = P.IDTIPOPIEZA

    	

        


